[project]
name = "gym_continual_rl"
version = "0.0.3"
dependencies = [
  "gymnasium==0.29.1",
  "numpy==1.26.4",
  "pygame==2.5.2"
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
packages = [
  "gym_continual_rl"
]

[tool.isort]
profile = "black"
